Resources:
  WSDynamoDbTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: order-status-ws
      BillingMode: PAY_PER_REQUEST
      StreamSpecification:
        StreamViewType: "NEW_AND_OLD_IMAGES"
      AttributeDefinitions:
        - AttributeName: ID
          AttributeType: S
        - AttributeName: outlet
          AttributeType: S
      KeySchema:
        - AttributeName: ID
          KeyType: HASH
        - AttributeName: outlet
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: "GSI"
          KeySchema:
            - AttributeName: "outlet"
              KeyType: "HASH"
          Projection:
            ProjectionType: "ALL"
