service: order-status

plugins:
  - serverless-bundle

package:
  individually: true

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  timeout: 30
  profile: ${file(../config.yml):PROFILE}
  region: ${file(../config.yml):REGION}
  environment:
    WS_TABLE_NAME: ${file(../config.yml):WS_TABLE_NAME}
    ORDER_TABLE_NAME: ${file(../config.yml):ORDER_TABLE_NAME}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: "*"
    - Effect: Allow
      Action:
        - execute-api:*
      Resource: "*"

functions:
  websocket-connect:
    handler: src/connect.handler
    events:
      - websocket:
          route: $connect
  websocket-disconnect:
    handler: src/disconnect.handler
    events:
      - websocket:
          route: $disconnect
  websocket-default:
    handler: src/default.handler
    events:
      - websocket:
          route: $default
  new-order:
    handler: src/newOrder.handler
    events:
      - http:
          path: /order
          method: post
          cors: true
  process-order:
    handler: src/processOrder.handler
    events:
      - stream: ${file(../config.yml):ORDER_TABLE_STREAM_ARN}
